export let data = [
  { num: "6.1", content: "구원열차 기관사 조치 " },
  { num: "6.2", content: "고장 열차 기관사 조치" },
  { num: "6.3", content: "고장ㆍ구원 열차 공통 사항" },
  { num: "6.4", content: "12JP선(점퍼선) 종류 " },
  { num: "6.5", content: "완전 부동 취급 시기" },
  { num: "6.6", content: "완전 부동 취급 방법 " },
  { num: "6.7", content: "전 편성 Pan 내리지 않고 완전 부동 취급 방법(1개 Unit 완전 부동 취급법) " },
  { num: "6.8", content: "연장 급전 시기" },
  { num: "6.9", content: "VCOS 취급 시기와 방법 " },
  { num: "6.9-1", content: "MTAR 여자시 현상" },
  { num: "6.10", content: "연장 급전 방법" },
  { num: "6.11", content: "전체 Pan 상승 불능 시 현상과 조치" },
  { num: "6.12", content: "1개 Unit Pan 상승 불능 시 현상 및 조치" },
  { num: "6.13", content: "전체 MCB 투입 불능 시 현상과 조치" },
  { num: "6.14", content: "1개 Unit MCB 투입 불능 시 현상 및 조치" },
  { num: "6.15", content: "동력 운전 불능 시 조치" },
  { num: "6.16", content: "비상제동이 작동되는 경우" },
  { num: "6.17", content: "비상제동 체결과 관련 있는 회로 차단기 또는 스위치" },
  { num: "6.18", content: "BVN1, BVN2 회로 차단기 복귀 불능 시 조치 " },
  { num: "6.19", content: "비상제동 완해 불능 시 현상 및 조치" },
  { num: "6.19-1", content: "EBCOS 투입하면 비상제동이 완해되는 경우" },
  { num: "6.19-2", content: "EBCOS취급 시, 보안장치(ATS, ATC, DSD 등) 및 열차분리 시 비상제동이 체결여부" },
  { num: "6.20", content: "주 공기압력 상승 불능(주 공기압력 저하) 시 현상 및 조치" },
  { num: "6.20-1", content: "차량 간 주 공기 누설 시 조치" },
  { num: "6.21", content: "주 공기압력 9.7kg/㎠(9kg/㎠) 이상 상승 시 현상 및 조치" },
  { num: "6.22", content: "TC차 전면 2지변 이후 주 공기압력 누설 시 현상 및 조치" },
  { num: "6.23", content: "주차제동 수동 완해 방법" },
  { num: "6.23-1", content: "BC 전체 완해 Cock를 차단하는 이유" },
  { num: "6.24", content: "제동 불완해 발생 시 조치" },
  { num: "6.24-1", content: "제동불안해 CPRS 취급 차량의 제동취급상태" },
  { num: "6.25", content: "보안제동 완해 불능 시 조치" },
  { num: "6.26", content: "Fault등 및 차측등(백색)이 점등되는 경우" },
  { num: "6.27", content: "SIV 고장 시, 원인과 현상 및 조치" },
  { num: "6.27-1", content: "SIV 전원 공급처" },
  { num: "6.28", content: "정지 위치 지나 정차 시 조치" },
  { num: "6.28-1", content: "폐색구간 점유의 기준" },
  { num: "6.29", content: "ATS 구간(하선 금정역. 상선 산본역) 출발신호 정지 시 조치" },
  { num: "6.30", content: "장시간 단전 시 조치" },
  { num: "6.31", content: "ASOS(특수 스위치) 취급 시기" },
  { num: "6.32", content: "상선 범계, 인덕원, 대공원역 진출 시 진로 개통 표시기 불량 시 조치" },
  { num: "6.33", content: "직류 전환(AC→DC) 시 MCB 양 소등 발생 시 조치" },
  { num: "6.34", content: "교류 전환(DC→AC) 시 MCB 양 소등 발생 시 조치" },
  { num: "6.35", content: "교류 모진 시 현상 및 조치" },
  { num: "6.36", content: "교·직류 전환 시 MCB ON등 계속 점등 시 조치" },
  { num: "6.37", content: "EPanDS 고착 또는 복귀 불능 시 조치" },
  { num: "6.37-1", content: "EPanDS 취급 시기" },
  { num: "6.38", content: "EGCS 고착 또는 복귀 불능 시 조치" },
  { num: "6.39", content: "임시 신호기 종류" },
  { num: "6.40", content: "임시 신호기 지나 동력 운전 시점" },
  { num: "6.41", content: "임시 신호기(서행 예고 신호기) 설치 지점" },
  { num: "6.42", content: "비상 전호 요령" },
  { num: "6.43", content: "기관사 안전장치(DSD)가 작동되지 않는 경우(DSD a접점)" },
  { num: "6.44", content: "EBCOS 투입 중 기관사 안전장치(DSD) 작동 관련" },
  { num: "6.45", content: "안산, 과천선 선로 최고 속도" },
  { num: "6.46", content: "지하 구간 운전 중 화재 발생 시 조치" },
  { num: "6.47", content: "출입문 고장에 따른 열차 회송 시" },
  { num: "6.48", content: "전체 출입문이 열리지 않는 경우" },
  { num: "6.49", content: "출입문 양 소등 현상" },
  { num: "6.50", content: "전ㆍ후부 운전실 DILPN 차단 후 복귀 불능 시 현상과 조치" },
  { num: "6.51", content: "1개 출입문이 닫히지 않을 때 조치" },
  { num: "6.52", content: "1개 출입문이 열리지 않을 때 조치" },
  { num: "6.53", content: "전체 출입문이 닫히지 않을 때 조치" },
  { num: "6.53-1", content: "출입문 기계적 접점 스위치 3개" },
  { num: "6.54", content: "BVN1, BVN2 차단 또는 HCRN 차단 시 조치" },
  { num: "6.55", content: "ATC 차상 장치 고장 시 현상 및 조치" },
  { num: "6.55-1", content: "ATC 장치 고장 시 취급" },
  { num: "6.56", content: "ATC 차단(ATCCOS 차단 취급)하는 경우와 운전 방법" },
  { num: "6.57", content: "ATC 구간 지시 속도 초과 시 운전 취급" },
  { num: "6.58", content: "ADU 차내 신호기에 정지(Stop)신호 현시될 수 있는 경우와 조치" },
  { num: "6.59", content: "VZ 고장 시(작동 불능 시) 현상" },
  { num: "6.59-1", content: "VZ에 대해 설명하시오" },
  { num: "6.60", content: "ATC 구간 대용 폐색 방식 시행 종류" },
  { num: "6.61", content: "ATS 구간에서 폐색신호기 정지신호일 경우의 운전" },
  { num: "6.62", content: "ATS 구간에서 15km/h 스위치를 취급하는 경우" },
  { num: "6.63", content: "ATSCOS 차단 취급을 하는 경우" },
  { num: "6.64", content: "교-교 전부 Pan이 절연구간에 정차시 현상 및 조치" },
  { num: "6.65", content: "교-직 절연 구간 정차 시 조치" },
  { num: "6.66", content: "과천선 VVVF 전동차 PanPS 압력" },
  { num: "6.67", content: "BCN과 VN 차단 시 현상" },
  { num: "6.68", content: "ATC 차상 장치 구성 요소" },
  { num: "6.69", content: "열차 화재로 정거장 외에서 승객 대피 시 조치" },
  { num: "6.70", content: "ATS 알람 벨(Alarm Bell)이 계속 작동 시" },
  { num: "6.71", content: "전차선 장애로 Pan 파손 시 현상 및 조치" },
  { num: "6.72", content: "전동 열차 편성 중 5개 차량 제동 불능 시 조치" },
  { num: "6.73", content: "축전지 전압이 낮을 경우 ACM 구동 방법" },
  { num: "6.73-1", content: "ACM 구동 불능시 현상 및 조치" },
  { num: "6.74", content: "대용 폐색 방식이란 " },
  { num: "6.75", content: "기관사가 운전실 이석 시 조치 " },
  { num: "6.76", content: "사고 시 열차 방호의 종류와 방법" },
  { num: "6.77", content: "임시신호기 설치 위치" },
  { num: "6.78", content: "전부운전실 ATCN 트립 발생 시 현상" },
  { num: "6.79", content: "DSD 작동하지 않는 경우" },
  { num: "6.80", content: "BVN1, 2 차단 시 현상" },
  { num: "6.81", content: "DOS의 DCS(출입문 닫힘 스위치) 접점 불량 시 조치" },
];
